//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteEmpresa
    {
        public ClienteEmpresa()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IDClienteEmpresa { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaUltimaOperacion { get; set; }
        public Nullable<double> Limite { get; set; }
        public string CUIT { get; set; }
        public string RazonSocial { get; set; }
        public string NombreFantasia { get; set; }
        public Nullable<int> IDTipoIVA { get; set; }
        public Nullable<int> IDDireccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaUltimaMod { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoMisc EstadoMisc { get; set; }
        public virtual TipoIVA TipoIVA { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
