//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.DocumentoDetalle = new HashSet<DocumentoDetalle>();
        }
    
        public int IDDocumento { get; set; }
        public Nullable<int> NrDocumento { get; set; }
        public Nullable<int> IDDocumentoTipo { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaContable { get; set; }
        public Nullable<int> IDClienteEmpresa { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public Nullable<int> IDUsuarioCreacion { get; set; }
        public Nullable<int> IDDocumentoRef { get; set; }
        public Nullable<int> IDEmpresaLocal { get; set; }
        public Nullable<int> CodigoExterno { get; set; }
        public string IPCreacion { get; set; }
        public Nullable<int> IDUsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string IPUltimaModificacion { get; set; }
    
        public virtual DocumentoTipo DocumentoTipo { get; set; }
        public virtual EmpresaLocal EmpresaLocal { get; set; }
        public virtual EstadoMisc EstadoMisc { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<DocumentoDetalle> DocumentoDetalle { get; set; }
    }
}
