//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoTipo
    {
        public DocumentoTipo()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int IDDocumentoTipo { get; set; }
        public string NombreDocumento { get; set; }
        public Nullable<int> UltimoNumero { get; set; }
        public string Letra { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<int> AfectaStock { get; set; }
        public Nullable<int> AfectaCC { get; set; }
        public Nullable<int> Debito { get; set; }
        public Nullable<int> AfectaContabilidad { get; set; }
        public Nullable<int> Credito { get; set; }
        public Nullable<int> UltimoNumeroManual { get; set; }
        public System.DateTime FechaUltimaMod { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
