//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaLocal
    {
        public int IDEmpresaLocal { get; set; }
        public string RazonSocial { get; set; }
        public string NombreFantasia { get; set; }
        public Nullable<int> IDDireccion { get; set; }
        public string CUIT { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    
        public virtual Direccion Direccion { get; set; }
    }
}
