//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoMisc
    {
        public EstadoMisc()
        {
            this.ClienteEmpresa = new HashSet<ClienteEmpresa>();
            this.Documento = new HashSet<Documento>();
            this.Producto = new HashSet<Producto>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IDEstado { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
    
        public virtual ICollection<ClienteEmpresa> ClienteEmpresa { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
