//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecio
    {
        public ListaPrecio()
        {
            this.PrecioDetalle = new HashSet<PrecioDetalle>();
        }
    
        public int IDListaPrecio { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaUltimaMod { get; set; }
    
        public virtual ICollection<PrecioDetalle> PrecioDetalle { get; set; }
    }
}
