//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public Localidad()
        {
            this.Direccion = new HashSet<Direccion>();
        }
    
        public int IDLocalidad { get; set; }
        public string Nombre { get; set; }
        public string CodigoPostal { get; set; }
        public int IDProvincia { get; set; }
    
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
