//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioDetalle
    {
        public PrecioDetalle()
        {
            this.DocumentoDetalle = new HashSet<DocumentoDetalle>();
        }
    
        public int IDPrecioDetalle { get; set; }
        public Nullable<int> IDListaPrecio { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaUltimaMod { get; set; }
    
        public virtual ICollection<DocumentoDetalle> DocumentoDetalle { get; set; }
        public virtual ListaPrecio ListaPrecio { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
