//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.PrecioDetalle = new HashSet<PrecioDetalle>();
        }
    
        public int IDProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IDProductoCategoria { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public Nullable<double> CostoActual { get; set; }
        public Nullable<double> CostoContable { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string UnidadMedida { get; set; }
        public System.DateTime FechaUltimaMod { get; set; }
    
        public virtual EstadoMisc EstadoMisc { get; set; }
        public virtual ICollection<PrecioDetalle> PrecioDetalle { get; set; }
        public virtual ProductoCategoria ProductoCategoria { get; set; }
    }
}
