//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoriaContable
    {
        public SubCategoriaContable()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
    
        public int IDSubCategoriaContable { get; set; }
        public string SubCategoriaContable1 { get; set; }
    
        public virtual ICollection<Cuenta> Cuenta { get; set; }
    }
}
