//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIVA
    {
        public TipoIVA()
        {
            this.ClienteEmpresa = new HashSet<ClienteEmpresa>();
        }
    
        public int IDTipoIVA { get; set; }
        public string Detalle { get; set; }
        public Nullable<double> Valor { get; set; }
    
        public virtual ICollection<ClienteEmpresa> ClienteEmpresa { get; set; }
    }
}
