//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Documento = new HashSet<Documento>();
            this.Documento1 = new HashSet<Documento>();
        }
    
        public int IDUsuario { get; set; }
        public string Nombre { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public Nullable<int> IDClienteEmpresa { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Idioma { get; set; }
        public Nullable<int> IDTipoUsuario { get; set; }
        public Nullable<System.DateTime> FechaUltimaMod { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ClienteEmpresa ClienteEmpresa { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Documento> Documento1 { get; set; }
        public virtual EstadoMisc EstadoMisc { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
