//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFITest4.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFITest4.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado.
        /// </summary>
        public static string AccesoError {
            get {
                return ResourceManager.GetString("AccesoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string activo {
            get {
                return ResourceManager.GetString("activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analizar Pedidos.
        /// </summary>
        public static string analizar {
            get {
                return ResourceManager.GetString("analizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string aprobar {
            get {
                return ResourceManager.GetString("aprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención!.
        /// </summary>
        public static string Atencion {
            get {
                return ResourceManager.GetString("Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido!.
        /// </summary>
        public static string bienvenido {
            get {
                return ResourceManager.GetString("bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora.
        /// </summary>
        public static string bitacora {
            get {
                return ResourceManager.GetString("bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        public static string calle {
            get {
                return ResourceManager.GetString("calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string CambiarPass {
            get {
                return ResourceManager.GetString("CambiarPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string cantidad {
            get {
                return ResourceManager.GetString("cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito.
        /// </summary>
        public static string carrito {
            get {
                return ResourceManager.GetString("carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito de compras.
        /// </summary>
        public static string carritoCompras {
            get {
                return ResourceManager.GetString("carritoCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string clientes {
            get {
                return ResourceManager.GetString("clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compre.
        /// </summary>
        public static string compre {
            get {
                return ResourceManager.GetString("compre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea cancelar? Perderá las modificaciones realizadas..
        /// </summary>
        public static string ConfimarCancelar {
            get {
                return ResourceManager.GetString("ConfimarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea realizar esta accion?.
        /// </summary>
        public static string confimarOperacion {
            get {
                return ResourceManager.GetString("confimarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string confirmar {
            get {
                return ResourceManager.GetString("confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controlar.
        /// </summary>
        public static string controlar {
            get {
                return ResourceManager.GetString("controlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string copiar {
            get {
                return ResourceManager.GetString("copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string crear {
            get {
                return ResourceManager.GetString("crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta Corriente.
        /// </summary>
        public static string cuentaCorriente {
            get {
                return ResourceManager.GetString("cuentaCorriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        public static string detalle {
            get {
                return ResourceManager.GetString("detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a disponible.
        /// </summary>
        public static string disponible {
            get {
                return ResourceManager.GetString("disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string dpto {
            get {
                return ResourceManager.GetString("dpto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor revise su contraseña.
        /// </summary>
        public static string errorCambioPass {
            get {
                return ResourceManager.GetString("errorCambioPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación no se pudo completar. Por favor logueese nuevamente.
        /// </summary>
        public static string ErrorLogInAgain {
            get {
                return ResourceManager.GetString("ErrorLogInAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación no se pudo completar. Revise los datos ingresados o logueese nuevamente.
        /// </summary>
        public static string ErrorNormal {
            get {
                return ResourceManager.GetString("ErrorNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura.
        /// </summary>
        public static string factura {
            get {
                return ResourceManager.GetString("factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturar.
        /// </summary>
        public static string facturar {
            get {
                return ResourceManager.GetString("facturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falso.
        /// </summary>
        public static string falso {
            get {
                return ResourceManager.GetString("falso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Alta.
        /// </summary>
        public static string fechaAlta {
            get {
                return ResourceManager.GetString("fechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Desde.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Emisión.
        /// </summary>
        public static string fechaEmision {
            get {
                return ResourceManager.GetString("fechaEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar:.
        /// </summary>
        public static string FiltrarTabla {
            get {
                return ResourceManager.GetString("FiltrarTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Última Modificación.
        /// </summary>
        public static string FUM {
            get {
                return ResourceManager.GetString("FUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El carrito ha sido guardado.
        /// </summary>
        public static string guardarCarrito {
            get {
                return ResourceManager.GetString("guardarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagina de Inicio.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string imagen {
            get {
                return ResourceManager.GetString("imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string ingresar {
            get {
                return ResourceManager.GetString("ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string inicioSesion {
            get {
                return ResourceManager.GetString("inicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string Invitado {
            get {
                return ResourceManager.GetString("Invitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingresar un motivo para esta acción.
        /// </summary>
        public static string justifacion {
            get {
                return ResourceManager.GetString("justifacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a esp.
        /// </summary>
        public static string Lenguaje {
            get {
                return ResourceManager.GetString("Lenguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limite.
        /// </summary>
        public static string limite {
            get {
                return ResourceManager.GetString("limite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string limpiar {
            get {
                return ResourceManager.GetString("limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El carrito ha sido limpiado.
        /// </summary>
        public static string limpiarCarrito {
            get {
                return ResourceManager.GetString("limpiarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de precios.
        /// </summary>
        public static string listaDetalle {
            get {
                return ResourceManager.GetString("listaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Precios.
        /// </summary>
        public static string listaPrecios {
            get {
                return ResourceManager.GetString("listaPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese a su cuenta.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugares.
        /// </summary>
        public static string lugares {
            get {
                return ResourceManager.GetString("lugares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido {0}, &lt;p&gt;Por favor verifica tu cuenta de usuario con el siguiente link:&lt;/p&gt;{1}.
        /// </summary>
        public static string MailValidationLink {
            get {
                return ResourceManager.GetString("MailValidationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número máximo de caracteres de &quot;{0}&quot; es: {1}.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string MenuConfiguracion {
            get {
                return ResourceManager.GetString("MenuConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string MenuIdioma {
            get {
                return ResourceManager.GetString("MenuIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número mínimo de caracteres de &quot;{0}&quot; es: {2}.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string monto {
            get {
                return ResourceManager.GetString("monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Fantasía.
        /// </summary>
        public static string nombreFantasia {
            get {
                return ResourceManager.GetString("nombreFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva.
        /// </summary>
        public static string nueva {
            get {
                return ResourceManager.GetString("nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string nuevo {
            get {
                return ResourceManager.GetString("nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña fué actualizada correctamente. Por favor ingrese nuevamente al sistema.
        /// </summary>
        public static string okCambioPass {
            get {
                return ResourceManager.GetString("okCambioPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación completada exitosamente..
        /// </summary>
        public static string OKNormal {
            get {
                return ResourceManager.GetString("OKNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidó su contraseña?.
        /// </summary>
        public static string olvidoPass {
            get {
                return ResourceManager.GetString("olvidoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese su usuario para recuperar su contraseña. Un link de recupero será enviado a su correo electrónico..
        /// </summary>
        public static string olvidoPassText {
            get {
                return ResourceManager.GetString("olvidoPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción cancelada!.
        /// </summary>
        public static string operacionCancelada {
            get {
                return ResourceManager.GetString("operacionCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido.
        /// </summary>
        public static string pedido {
            get {
                return ResourceManager.GetString("pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piso.
        /// </summary>
        public static string piso {
            get {
                return ResourceManager.GetString("piso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string precio {
            get {
                return ResourceManager.GetString("precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precios.
        /// </summary>
        public static string precios {
            get {
                return ResourceManager.GetString("precios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Unitario.
        /// </summary>
        public static string precioUnitario {
            get {
                return ResourceManager.GetString("precioUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alguno/s precios de su prepedido han sido actualizados a los nuevos valores vigentes.
        /// </summary>
        public static string PrePedidoActualizado {
            get {
                return ResourceManager.GetString("PrePedidoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string prevPass {
            get {
                return ResourceManager.GetString("prevPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        public static string producto {
            get {
                return ResourceManager.GetString("producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string ProvinciaTitle {
            get {
                return ResourceManager.GetString("ProvinciaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puedes arrastrar las fotos del producto para agregarlas al carrito.
        /// </summary>
        public static string pss {
            get {
                return ResourceManager.GetString("pss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón social.
        /// </summary>
        public static string razonSocial {
            get {
                return ResourceManager.GetString("razonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string rechazar {
            get {
                return ResourceManager.GetString("rechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrese.
        /// </summary>
        public static string registro {
            get {
                return ResourceManager.GetString("registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña y la contraseña de confirmación no coinciden.
        /// </summary>
        public static string RepeatPasswordCheck {
            get {
                return ResourceManager.GetString("RepeatPasswordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo &quot;{0}&quot; no puede estar vacío.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verifique Usuario/Contrasena.
        /// </summary>
        public static string RevisarUsuarioContra {
            get {
                return ResourceManager.GetString("RevisarUsuarioContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su carrito de compras .
        /// </summary>
        public static string suCarrito {
            get {
                return ResourceManager.GetString("suCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo IVA.
        /// </summary>
        public static string tipoIVA {
            get {
                return ResourceManager.GetString("tipoIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Usuario.
        /// </summary>
        public static string tipoUsuario {
            get {
                return ResourceManager.GetString("tipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Producto.
        /// </summary>
        public static string TotalProducto {
            get {
                return ResourceManager.GetString("TotalProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por.
        /// </summary>
        public static string usuarioCreacion {
            get {
                return ResourceManager.GetString("usuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, el nombre de usuario no se encuentra disponible.
        /// </summary>
        public static string UsuarioExistente {
            get {
                return ResourceManager.GetString("UsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra disponible.
        /// </summary>
        public static string UsuarioExistenteOK {
            get {
                return ResourceManager.GetString("UsuarioExistenteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no se encuentra habilitado para ingresar al sistema.
        /// </summary>
        public static string UsuarioNoHabilitado {
            get {
                return ResourceManager.GetString("UsuarioNoHabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario última modificación.
        /// </summary>
        public static string UUM {
            get {
                return ResourceManager.GetString("UUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vacio.
        /// </summary>
        public static string vacio {
            get {
                return ResourceManager.GetString("vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string ver {
            get {
                return ResourceManager.GetString("ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verdadero.
        /// </summary>
        public static string verdadero {
            get {
                return ResourceManager.GetString("verdadero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string volver {
            get {
                return ResourceManager.GetString("volver", resourceCulture);
            }
        }
    }
}
